[project]
name = "jupyterlab-save-notebook-state-bug-example"
version = "0.1.0"
description = "Add a short description here"
authors = ["Kyle Barron <kyle@developmentseed.org>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
jupyterlab = ">=4.1.8,<4.2"
ipykernel = ">=6.29.3,<6.30"
lonboard = ">=0.8.0,<0.9"
nbconvert = ">=7.16.3,<7.17"
